# Generated by Django 3.0.6 on 2021-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('college', models.TextField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
