# Generated by Django 3.1.5 on 2021-01-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=10)),
                ('collegeid', models.CharField(max_length=11)),
            ],
        ),
    ]
