# Generated by Django 3.0.6 on 2021-01-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_suggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='email',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
