# Generated by Django 3.0.6 on 2021-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_suggest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
