# Generated by Django 3.1.5 on 2021-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('heading', models.TextField()),
                ('curatedby', models.CharField(max_length=50)),
                ('date', models.CharField(help_text='Enter date in format 28 March,2020', max_length=50)),
                ('tags', models.CharField(help_text='Energy Polythene', max_length=10)),
                ('summary', models.TextField()),
            ],
        ),
    ]
