# Generated by Django 3.1.5 on 2021-01-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='articles',
        ),
    ]
