# Generated by Django 3.1.5 on 2021-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210117_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.CharField(help_text='Energy Polythene', max_length=100),
        ),
    ]
