# Generated by Django 3.1.5 on 2021-01-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210117_1320'),
        ('home', '0004_questionpaper'),
    ]

    operations = [
    ]
