# Generated by Django 3.1.5 on 2021-01-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20210117_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='peerlearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('heading', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('date', models.CharField(help_text='Enter date in format 28 March,2020', max_length=50)),
                ('tags', models.CharField(help_text='Energy Polythene', max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='questionpaper',
        ),
        migrations.DeleteModel(
            name='suggest',
        ),
    ]
