# Generated by Django 3.1.5 on 2021-01-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_upcomingpeerlearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
