# Generated by Django 3.1.5 on 2021-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210118_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qualification1', models.CharField(max_length=100)),
                ('qualification2', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='facultys/')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('studentname', models.CharField(max_length=50)),
                ('branchname', models.CharField(max_length=50)),
                ('experience', models.TextField()),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
    ]
