# Generated by Django 3.1.5 on 2021-01-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_samplepaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curators', models.CharField(help_text='Names separated by commas:- Abhinav,Neha,Nikhil', max_length=200)),
                ('newsletterpdf', models.FileField(upload_to='newsletters/')),
                ('editionmonth', models.CharField(help_text='Published Month Name:- December', max_length=200)),
            ],
        ),
    ]
