# Generated by Django 3.1.5 on 2021-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventupdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.TextField()),
            ],
        ),
    ]
